### ISSUE TITLE
Pac4JSecurityFeature should look for annotations in superclass/interface

### ISSUE THREAD

**Issue by andriusvelykis** [pac4j/jax-rs-pac4j#10]
I am having trouble with `@Pac4JSecurity` annotations not being located on resource class/methods when the resource class had been dynamically extended (e.g. via a `javassist` `ProxyFactory`).

The annotation getters in [`Pac4JSecurityFeature`](https://github.com/pac4j/jax-rs-pac4j/blob/9066cf4b42fadee15de9d6c3dcfdd8398b2deac5/src/main/java/org/pac4j/jax/rs/features/Pac4JSecurityFeature.java#L58) only check the class itself for annotations and does not continue with superclass or interface. In comparison, similar `DynamicFeature` implementations in Jersey use [`org.glassfish.jersey.server.model.AnnotatedMethod`](https://github.com/jersey/jersey/blob/562bd63513cdfba9fce7556808926ca29f38cfe2/core-server/src/main/java/org/glassfish/jersey/server/model/AnnotatedMethod.java) utility class (or other similar reflection utils), which has a more elaborate logic of locating annotations. Could something like that be ported/reused in `jax-rs-pac4j`?

The actual issue cropped up when using `dropwizard-pac4j` in a Dropwizard application with a subresource instantiated via a `UnitOfWorkAwareProxyFactory` (suggested as a workaround in dropwizard/dropwizard#1806). This creates a proxy subclass of a sub-resource and the pac4j annotations are lost. 

While that use case would go away with some future version of Dropwizard, the general problem with `Pac4JSecurityFeature` as described should still be valid in general.

**Comment by victornoel** [comment]
Yes, that makes sense!

I will look at it tomorrow. The only thing is that I don't want to rely on `AnnotatedMethod` from Jersey because we have to support any JAX-RS runtime, but I don't think this is a too complex functionality to implement.

Thanks :)

**Comment by victornoel** [comment]
@andriusvelykis could you check that everything is ok with the latest SNAPSHOT? (you can retrieve it from sonatype's OSS Snapshot repository, documented in the README)

**Comment by andriusvelykis** [comment]
Thanks - just checked, seems to be working in my case!

**Comment by victornoel** [comment]
Great, I will let it steep for a few days and also see if you don't find other bugs or limitation and then we will release a new version then :)

**Comment by victornoel** [comment]
@andriusvelykis do you need it released with version 1.0.1 or can you wait for the next 1.1.0 which will include some new features and be released in a few weeks?

**Comment by andriusvelykis** [comment]
No rush for me - feel free to release as 1.1.0. Thanks!
