### ISSUE TITLE
Support Pac4j 5

### ISSUE THREAD

**Issue by orangecoding** [pac4j/jax-rs-pac4j#151]
When booting this with Pac4J 5, we're getting `org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: 'java.lang.Object org.pac4j.core.engine.SecurityLogic.perform`

**Comment by leleuj** [comment]
You can't use pac4j v5 with jax-rs-pac4j as it has not been upgraded yet.

**Comment by orangecoding** [comment]
yes, I'm aware of that. I have seen this in the pom. I was wondering when you're planning to upgrade jax-rs-pac4j to be usable with pac4j 5.

**Comment by leleuj** [comment]
It's not planned yet. After this summer for sure.
