### ISSUE TITLE
NullPointerException on DefaultCallbackLogic

### ISSUE THREAD

**Issue by halflite** [pac4j/jax-rs-pac4j#22]
jersey-mvc-freemarker 2.25.1
jersey-container-grizzly2-servlet 2.25.1
grizzly-http-servlet 2.3.28
jax-rs-pac4j 2.0.0
pac4j-oauth 2.0.0

https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/engine/DefaultCallbackLogic.java

Method redirectToOriginallyRequestedUrl

> context.setSessionAttribute(Pac4jConstants.REQUESTED_URL, null);

https://github.com/javaee/grizzly/blob/master/modules/http-server/src/main/java/org/glassfish/grizzly/http/server/Session.java

Grizzly SessionStore cache attribute uses ConcurrentHashMap. Null value is denied.

**Comment by victornoel** [comment]
Good find, so I will commit a simple fix soon, but until it is released, you can workaround this problem by doing the following:

Override `GrizzlySessionStore` to fix the problem:
```java
    public class FixGrizzlySessionStore extends GrizzlySessionStore {
        @Override
        public void set(JaxRsContext context, String key, Object value) {
            if (value == null) {
                getSession(context).removeAttribute(key);
            } else {
                super.set(context, key, value);
            }
        }
    }
```

And use it instead of the original one by setting it on the pac4j Config:
```java
        config.setSessionStore(new FixGrizzlySessionStore());
```

And it should be good :)

**Comment by leleuj** [comment]
I remember some discussion on this kind of issue for the `ProfileManager` used in Play (as the profiles are saved in the Play Cache which does not support `null` in some implementations).
We ended up putting empty values: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/client/IndirectClient.java#L102

**Comment by victornoel** [comment]
@leleuj in this case it is clearly not needed as there is a `removeAttribute` method exactly for this purpose…

**Comment by victornoel** [comment]
@leleuj also I think it is the context or the session store that should bother with that, not their clients… it's not their problem how things are stored.

**Comment by leleuj** [comment]
Yes, it was a specific store and thus you need to handle that by yourself...

**Comment by victornoel** [comment]
ah ok, but it's ok right now, it's fixed.
