### ISSUE TITLE
Update pac4j-core dependency to 1.9.9 in jax-rs-pac4j 1.2.1

### ISSUE THREAD

**Issue by sebargarcia** [pac4j/jax-rs-pac4j#25]
The version jax-rs-pac4j 1.2.1 point to pac4j core 1.9.6 instead of the last version 1.9.9

**Comment by victornoel** [comment]
This is normal, it is because it was released just after pac4j 1.9.6.

Nothing prevent you from using another 1.9.x version of pac4j by using maven's dependency management in your own project.
