### ISSUE TITLE
MediaType compare problem

### ISSUE THREAD

**Issue by hello-ming** [pac4j/jax-rs-pac4j#27]
In this file  jax-rs-pac4j/src/main/java/org/pac4j/jax/rs/pac4j/JaxRsContext.java

 161           if (MediaType.APPLICATION_FORM_URLENCODED
 162                   .equalsIgnoreCase(Objects.toString(requestContext.getMediaType()))) {

when media type contains charset info(e.g. application/x-www-form-urlencoded;charset=UTF-8),
formdata will not be available.

I have this issue when useing ajax to post data instead of form submit, of cource, i can set contentType to bypass it.

Just wondering if it is possible to compare with starstWith or another way.

It's frustrating for a newbie of pac4j.

**Comment by victornoel** [comment]
yep, there seems to be a bug, good find! I will take a look at it quickly

**Comment by victornoel** [comment]
@hello-ming would you be so kind as to test if your problem is fixed with latest snapshot (see https://github.com/pac4j/jax-rs-pac4j#development)? Thanks :)
