### ISSUE TITLE
Release 2.3.0 and 3.0.0

### ISSUE THREAD

**Issue by victornoel** [pac4j/jax-rs-pac4j#44]
@leleuj could we release both 2.3.0 and 3.0.0? And then for dropwizard-pac4j as well?

In particular, I fixed a embarrassing bug (cf release notes ;) that someone reported to me.

**Comment by leleuj** [comment]
No problem. I will do that soon.

**Comment by leleuj** [comment]
It's in progress, I'll keep you posted...

**Comment by leleuj** [comment]
I started the Dropwizard releases this morning, they will show up during the day in the Maven central repository, the jax-rs-pac4j releases are already available.

**Comment by victornoel** [comment]
thanks @leleuj :)

**Comment by leleuj** [comment]
@victornoel I let you post the releases announcements on the pac4j-announce mailing list: https://groups.google.com/forum/?fromgroups#!forum/pac4j-announce Thanks

**Comment by victornoel** [comment]
@leleuj done :)
