### ISSUE TITLE
Error in README.md?

### ISSUE THREAD

**Issue by hdeadman** [pac4j/jax-rs-pac4j#46]
The following from the readme doesn't compile:
```
config.getClients().setCallbackUrlResolver(new JaxRsUrlResolver());
```

Should it be the following?
```
config.getClients().setUrlResolver(new JaxRsUrlResolver());
```

**Comment by leleuj** [comment]
Yes. The `JaxRsUrlResolver` is an `UrlResolver`. Would you mind opening a PR? Thanks

**Comment by victornoel** [comment]
@hdeadman thanks for the feedback :)
