### ISSUE TITLE
Demo for jax-rs-pac4j ? 

### ISSUE THREAD

**Issue by akumar2812** [pac4j/jax-rs-pac4j#47]
This is not an issue but is there a demo for jax-rs-pac4j ?

**Comment by leleuj** [comment]
I can create a `jax-rs-pac4j-demo` Github repository if necessary...

**Comment by victornoel** [comment]
@leleuj I would keep a folder named "sample" or something like that in this repository. With a separated one, it is hard to keep things synchronized between the code and the sample and we don't see it break as easily.

**Comment by leleuj** [comment]
No problem. Your way.

**Comment by akumar2812** [comment]
Thanks guys... appreciate it!

**Comment by gowridev** [comment]
@leleuj @victornoel  Could you please share updates/link for demo for jax-rs-pac4j (if possible for example for  jax-rs-pac4j using resteasy for wildfly server)

**Comment by victornoel** [comment]
@gowridev I'm sorry I don't have the time anymore to maintain this module. But if you make some demos I'm sure we will be able to include them. In pac4j usually the demo are in their own repository, you should even make one specific for resteasy for wildfly server.

**Comment by leleuj** [comment]
@victornoel sad to hear that

@gowridev if you propose a demo, I can create the appropriate repo for that: xxx-pac4j...

**Comment by tsmalls93** [comment]
@leleuj, I would also be interested in a demo. I would like to see a demo app that shows how to secure a simple REST resource with the `isAuthenticated` authorizer using `AzureAdClient`. I would also be interested in seeing how to use a role/group from Azure AD to secure a REST resource.

**Comment by leleuj** [comment]
Many people would like to have a demo for this implementation. Maybe I'll create one when upgrading to pac4j v4.
But above all, this is open source, the project relies on YOUR contributions.

**Comment by tsmalls93** [comment]
I understand. If/when I get it working, I would be happy to contribute.

**Comment by leleuj** [comment]
Sure. Your contribution is welcome.
