### ISSUE TITLE
Unable to set expires attribute in Cookie

### ISSUE THREAD

**Issue by davoustp** [pac4j/jax-rs-pac4j#49]
This is the JAXRS-pac4j counterpart of issue https://github.com/pac4j/pac4j/issues/1356.

This issue is about leveraging the additional expiry attribute added to the `Cookie` class in pac4j-core by https://github.com/pac4j/pac4j/issues/1356, and set the corresponding cookie attribute if specified.

Pending pull request, but requires that issue 1356 @ pacj4j is merged and release (dependancy update is of course required).

**Comment by davoustp** [comment]
Pull request created now that pac4j 3.8.0 is out.

**Comment by leleuj** [comment]
Fixed in v3.0.1.
