### ISSUE TITLE
Populate the SecurityContext

### ISSUE THREAD

**Issue by victornoel** [pac4j/jax-rs-pac4j#7]
See undertow-pac4j and do something similar

**Comment by leleuj** [comment]
Yes, the idea is to use a specific `ProfileManager`. `spring-security-pac4` and `buji-pac4j` follow the same logic.

**Comment by victornoel** [comment]
I guess there is some thinking to do with respect to the underlying container... in JAX-RS there is the `SecurityContext` and by default it returns the Principal from the underlying servlet request, or for example with Grizzly, the Principal contained in the Grizzly request.

Two possibilities (non-exclusive):
- set our own `SecurityContext`
- handle that at the underlying container level (when possible) so that people can still rely on the underlying container behaviour w.r.t. security and roles...

btw @leleuj in j2e-pac4j, shouldn't he `HttpServletRequest`'s `Principal` be set with pac4j authentication/authorization informations? Or is it already?

**Comment by victornoel** [comment]
Anohter question @leleuj: why in undertow-pac4j, the security context is populated on `retrieveAll` and not on `save`? I would have thought it should be at last on `save`, so that after both indirect client and direct client, the security context is populated.
And I guess actually also on `retrieveAll` during access of urls protected by indirect clients.

I think I will do that for `jax-rs-pac4j`!

**Comment by victornoel** [comment]
That's not so obvious to do as I thought it was ^^ in the end I did as in undertow-pac4j.

The interplay of  profile in session or not is not easy to deal with... I think there may be corner cases where there would be a profile stored in session and one not stored in session (in case of multiprofile) and depending on the order of the clients of the filter, then the `SecurityContext` would be different (because it would be loaded based on the parameter `readFromSession` itself based on the clients used for authentication...).

Another solution would be to incrementally populate the `SecurityContext` based on calls to `save` and to `retrieveAll`... still I'm not so happy with the way the `ProfileManager` works :)

**Comment by leleuj** [comment]
The default way to save / get the profile is to use the `ProfileManager`: for indirect clients, user profiles are saved into the web session while for direct clients, they are saved in the request attributes (or equivalent).

In j2e-pac4j, we use the regular `ProfileManager` and thus, we don't populate the `Principal` of the `HttpServletRequest`, but this could be an improvement: in that case, we would certainly have a `J2EProfileManager` to do that.

So, should it be done on `save` or `retrievelAll`? It depends on the capabilities of the framework and the way it manages the security context.

In Undertow, I didn't find a real storage layer, the security context seems to be populated at every request, though it might be my limited understanding. Thus, I override the `retrieveAll` method.
When there is a real storage (Spring Security and Shiro), it's done during the `save` call: user profiles are saved in both the *pac4j* and framework-specific way.
