### ISSUE TITLE
jersey 2.29+ breaks Pac4JValueFactoryProvider

### ISSUE THREAD

**Issue by gneuvill** [pac4j/jax-rs-pac4j#73]
See https://github.com/eclipse-ee4j/jersey/pull/4091

Enum `Parameter$Source` has moved from `org.glassfish.jersey.server.model` to `org.glassfish.jersey.model.Parameter`

**Comment by leleuj** [comment]
OK. What's your proposal on this? We already have a `jersey225` module...

**Comment by victornoel** [comment]
Just to chip in but I wouldn't be able to help, the solution would be to introduce another submodule for this jersey version yes.
It's not very hard to do, just copy the existing one and adapt it so that it works with jersey 2.29+, there should be tests and everything else already implemented.

**Comment by leleuj** [comment]
@victornoel Thanks for the hint. Let's hope there won't be too many breaking changes in Jersey...

@gneuvill How do you feel about this solution? Can you submit a PR? Thanks
