### ISSUE TITLE
Cut version with #74

### ISSUE THREAD

**Issue by richeyh** [pac4j/jax-rs-pac4j#75]
https://github.com/pac4j/jax-rs-pac4j/pull/74

the readme already says: 
for Jersey (>=2.29) : the jersey-pac4j library (groupId: org.pac4j, version: 3.0.2)

but https://mvnrepository.com/artifact/org.pac4j/jersey-pac4j
only shows version 3.0.1 which does not have the fix in #74 that resolves the issue with jersey 2.30.1 

so can we get version 3.0.2 cut to align with the docs and get the fix released

**Comment by leleuj** [comment]
I just cut the release, the version 3.0.2 will show up in the Maven central repo in a few hours.
