### ISSUE TITLE
Updating to pac4j 4.x?

### ISSUE THREAD

**Issue by doodleincode** [pac4j/jax-rs-pac4j#81]
Are there plans to update the jax-rs implementation to use pac4j 4.x?

**Comment by leleuj** [comment]
Sure. It's planned after the upgrade of vertx-pac4j. It could be in June or in September/October.

**Comment by doodleincode** [comment]
Ok, thanks for the update.

**Comment by leleuj** [comment]
Let's keep that issue opened. The work is still to be done...
